name: letter_a
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  dotted_border: ^2.1.0
  google_sign_in: ^6.2.1
  sign_in_button: ^3.2.0
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  open_file: ^3.3.2
  path_provider: ^2.1.3
  file_picker: ^8.0.5
  dio: ^5.4.3+1
  image_picker: ^1.1.2
  intl: ^0.19.0
  url_launcher: ^6.3.0
  flutter_local_notifications: ^17.2.2
  flutter_rating_bar: ^4.0.1
  flutter_masked_text2: ^0.9.1
  permission_handler_html: ^0.1.3+2
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.15
  open_filex: ^4.5.0
  uuid: ^4.5.0
  cached_network_image: ^3.4.1
  googleapis: ^13.2.0
  http_parser: ^4.0.2
  mime: ^1.0.6
  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900